validate:
  user:
    email:
      format: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
      length:
        max: 255
    name:
      length:
        max: 50

  # locales
available_locales: [ "en", "vi" ]
default_locale: "en"

# client
client:
  host: "localhost:3000"
