validate:
  user:
    email:
      format: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      length:
        max: 255
    name:
      length:
        max: 50
    password:
      length:
        min: 6
      expire:
        hours: 2
user:
  gravatar:
    size: 80
micropost:
  content:
    length:
      max: 140
  image:
    content_type:
      - image/jpg
      - image/jpeg
      - image/png
      - image/gif
    size:
      max: 5
    resize: [200, 200]

pagy:
  items: 10

  # locales
available_locales: [ "en", "vi" ]
default_locale: "en"

# client
client:
  host: "localhost:3000"
